apiversion: app/v1
kind: deployment
metadata:
  name: my-deployment
  spec:
    replicas: 1
    selector:
      matchlables: 
        app: my-app
    template:
      metadata: 
        lables: 
          app: my-app
      spec:
        containers:
        - name: my-container
          image: nginx:latest
          ports:
          - containerport: 8080