apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-ndp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-ndp
  template:
    metadata:
      labels:
        app: my-app-ndp
    spec:
      containers:
      - name: my-app-container
        image: nginx:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-app-ndp
  labels:
    app: my-app-ndp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: my-app-ndp
    
  

      
