# This is a basic workflow to help you get started with Actions
name: myinfra- DEV 

on:
  workflow_dispatch: # Workflow_dispatch event if you want to be able to manually run this workflow from the UI
  push:
    branches: ["main"]

permissions:
      id-token: write
      contents: read

env:
  ARM_SUBSCRIPTION_ID: 02

jobs:
  deploy_dev: 
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        working-directory: .

    env:
      ARM_CLIENT_ID: ${{ secrets.TF_ARM_CLIENT_ID }} #It's specific to DEV. So need to replace it with appropriate value for each environment.
      ARM_CLIENT_SECRET: ${{ secrets.TF_ARM_CLIENT_SECRET }} #It's specific to DEV. So need to replace it with appropriate value for each environment.
      Terraform-RG-SUFFIX: DEV
      Terraform-RG: RG-DEV-EU-CTSHARED-001
      

    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        run: az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID}} --password ${{ secrets.AZURE_SECRET_ID }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: 'Get RG with powershell action'
        uses: azure/powershell@v1
        with:
           inlineScript: |
              Get-AzResourceGroup
           azPSVersion: "latest"
